#include "emitter.hpp"

void emit_typst(std::ostream &out, const Document &doc,
                const std::string &code_lang, const std::string &filename) {
  out << "// Generated by noweb-typst\n\n";
  out << "#set heading(numbering: \"1.1\")\n\n";
  out << "#let today = datetime.today()\n\n";

  out << "#set page(header: context [ #set text(10pt); #today.display(\"[month "
         "repr:long] [day], [year]\")#h(1fr)`"
      << filename << "`#h(1cm)" << "#counter(page).display()])\n\n";

  for (const auto &block : doc.blocks) {
    if (block.kind == Block::Kind::CodeDefn) {
      out << "#block(breakable: false)[\n";

      // header
      out << "$chevron.l$_"
          << (block.name.empty() ? "_Unnamed chunk" : block.name)
          << "_$chevron.r#h(-0.1em)eq.triple$ \\ ";

      bool in_code = false;

      for (const auto &line : block.body) {
        switch (line.kind) {
        case Line::Kind::Text: {
          if (line.text.empty())
            break;

          if (!in_code) {
            out << "```" << code_lang << "\n";
            in_code = true;
          }

          out << "    " << line.text << '\n';
          break;
        }

        case Line::Kind::Use: {
          if (in_code) {
            out << "```\n"; // close code block
            in_code = false;
          }
          out << "#h(1.5em)$chevron.l$_" << line.name << "_$chevron.r$ \\ ";
          break;
        }
        }
      }

      if (in_code) {
        out << "```\n";
      }

      out << "]\n\\ "; // spacing between chunks
    } else {
      // Doc block
      out << block.docsText << "\n";
    }
  }
}
