#include "emitter.hpp"

void emit_typst(std::ostream& out, const Document& doc, const std::string& code_lang) {
    out << "// Generated by noweb-typst\n\n";
    for (const auto& block : doc.blocks) {
        if (block.kind == Block::Kind::Code) {
            out << "== ";
            if (block.text.empty())
                out << "Unnamed chunk\n\n";
            else
                out << block.name << "\n\n";

            out << "```" << code_lang << "\n";
            out << block.text;
            if (block.text.empty() || block.text.back() != '\n')
                out << '\n';

            out << "```\n\n";

        } else {
            out << block.text << "\n";
        }
    }
}